### PR TITLE
remove unused namespace

### PR DESCRIPTION
**Pull request by plesiecki**
Hi,
Let's support namespace at-rule. I found it useful.

### CODE REVIEW

**Comment by ben-eb** [comment]
Nice idea; but I don't think the implementation is right. We can detect if *named* namespaces are used if no selectors have that namespace. For example, this example's `@namespace` is used:

```css
@namespace svg url(http://www.w3.org/2000/svg);

svg|a {
  color:blue
}
```

So is this:

```css
@namespace svg url(http://www.w3.org/2000/svg);

*|a {
  color:blue
}
```

But this is unused:

```css
@namespace svg url(http://www.w3.org/2000/svg);

a {
  color:blue
}
```

MDN has a good explanation of this: https://developer.mozilla.org/en-US/docs/Web/CSS/@namespace

In general also, if you could leave the original tests alone and just define new ones instead that'd be awesome. More tests are better than fewer. :smile:

**Comment by plesiecki** [comment]
dunno why does CI keep failing

**Comment by ben-eb** [comment]
Fixed CI, it's due to babel-tape-runner 1.3.0. Going to upgrade to ava soon. :smile:

I'll review this after I've eaten.

**Comment by ben-eb** [comment]
Looks great to me! Thanks very much. :+1:

**Comment by plesiecki** [comment]
Cool. Thanks for your comments. Glad I could contribute.

**Comment by ben-eb** [comment]
https://github.com/ben-eb/postcss-discard-unused/commit/30a468955e59a7c93de949ae49ba76b739144ec4

Released in v2.2.0. :+1:

**Pull request closed without merging**
